DEbinger/CEGS

README.md
=> added message to readme

archive_data/hotel_data/hnl_airport.json, archive_data/hotel_data/hnl_city.json, archive_data/hotel_data/jfk_airport.json, archive_data/hotel_data/jfk_city.json, archive_data/hotel_data/lax_airport.json, archive_data/hotel_data/lax_city.json
- create new dir in archive_data subdir called hotel_data
- add json files with hotel search results based on airport codes for HNL, LAX, and JFK
- add json files with hotel search results based on coordinates for Honolulu, Los Angeles, and New York City just in case the data is different from Airport.
closes #22
=> Get Hotel Data

archive_data/car_data/hnl_airport.json, archive_data/car_data/honolulu_city.json, archive_data/car_data/jfk_airport.json, archive_data/car_data/lax_airport.json, archive_data/car_data/losangeles_city.json, archive_data/car_data/newyork_city.json
using airports (hnl, lax, jfk) and city coordinates (honolulu, los angeles, new york city)
resolves #23
=> gathered car data

package.json, server/lib/carsReq.js, server/lib/flightsReq.js, server/lib/hotelsReq.js, server/routes/carRoute.js, server/routes/flightsRoute.js, server/routes/hotelRoute.js, server/server.js
- could only do basic routes for each for now, will do rest when database is ready.
- created http requests for list view for all and detail view for hotels
resolves #31
=> created basic routes for hotel, cars, flights and http requests

server/migrations/20170413080905-add-security-answer-to-user.js, server/migrations/20170413081155-update-itinerary-to-gallery.js, server/models/gallery.js, server/models/itinerary.js, server/models/user.js
- created migration to add security_answer column to User models
- created migration to give foreign key to column itinerary in Gallery models
resolves #42
=> Update User and Gallery Models

client/src/redux/actions/index.js, client/src/redux/reducers/index.js
- also added security_answer to redux action and reducer
resolves #53
=> refactored redux to match db schema

client/src/components/ResetPassword.js, client/src/components/SignIn.js, client/src/components/SignUp.js, client/src/index.js
- revise existing sign up form to include appropriate input types
- create sign in form
- include a link to reset page for guest to reset password
resolve #52
=> Creat User Forms

client/src/components/ResetPassword.js, client/src/components/SignIn.js, client/src/components/SignUp.js
- update input placeholder values
- include input buttons for Google and Facebook
- need to implement OAuth for Google and Facebook
- downloaded Google login button design assets
- need to get Javascript code for Facebook login button or design custom button that complies with Facebook branding guidelines
closes #52
=> Update Sign In Sign Up Forms

client/src/components/Cars.js, client/src/components/Flights.js, client/src/components/Hotels.js, client/src/components/ResetPassword.js, client/src/components/SignIn.js, client/src/components/SignUp.js
- setup forms to search flights, hotels, and cars
- not setup to make requests
- setup values for each input to connect to the databse and API requests
resolves #59
=> Setup Forms

client/public/index.html, client/src/index.css
added globe D3 css and html srcs
=> added globe D3 css and html srcs

client/package.json, client/src/components/SignUp.js, client/src/containers/App.js, client/src/redux/reducers/usersReducer.js, server/lib/userReq.js, server/routes/userRoute.js, server/server.js
- created functions to post user info to databse upon sign up
- initial submits returned null values
- debugged and found users parameter wasn't passing into the signUpReq function
- need to clean up code
resolves #59
=> Sign up data posts to database

client/package.json, client/src/components/SignUp.js, client/src/index.js, client/src/redux/actions/usersAction.js, client/src/redux/reducers/usersReducer.js, server/routes/userRoute.js, server/server.js
- able to validate sign up on server side
- working on validating user sign up on client side using redux
- not passing correct if statement in userReducer
- need data prior to passwords hashing to validate on client side
resolves #60
=> Validate Sign Up Form

client/src/components/Nav.js, client/src/components/Profile.js, client/src/components/SignIn.js, client/src/components/SignUp.js, client/src/index.js, client/src/redux/actions/usersAction.js, client/src/redux/reducers/usersReducer.js, server/routes/userRoute.js
- render a single element on Profile component
- store not adding new user to state
- debug store with help from Nakaz and Jon
- used redux devtools to debug
- updated actions and reducers
resolves #59
=> Working on Profile and Debug Store

client/lib/userReq.js, client/src/components/Profile.js, client/src/components/ResetPassword.js, client/src/components/SignUp.js, client/src/index.js, client/src/redux/actions/usersAction.js, server/routes/userRoute.js
- use map function to render values
- update security question values
resolves #59
=> Render user data in Profile

client/src/components/CarsForm.js, client/src/components/Nav.js, client/src/components/Profile.js, client/src/components/SignIn.js, client/src/index.js, client/src/redux/actions/carsAction.js, client/src/redux/reducers/usersReducer.js
- fixed mergies in Profile, SignIn, CarsForms
- usersReducer file was reverted to the old code in the last pull request
- refactored using old code based on my last PR
resolves #59
=> Fixed merge conflicts

client/src/redux/actions/carsAction.js
=> Updated carsActions

client/lib/userReq.js, client/src/components/SignIn.js, client/src/components/SignUp.js
- fixed the data in the data variable in userReq.js
- updated autocomplete to autoComplete in SignIn component in the email and password input fields
- went through git logs to retrieve code for SignUp component that was overwritten
resolves #59
=> Updated User components that were overwritten

client/src/components/Itinerary.js, server/server.js
- Will only work if a user is redirected to a detailed listing of a hotel.
resolves #59
=> Render Hotel Details in Itinerary Component

client/package.json, client/src/components/Cars.js, client/src/components/CarsDetails.js, client/src/components/CarsForm.js, client/src/components/Sidebar.js, client/src/index.js, client/src/redux/actions/carsAction.js, client/src/redux/reducers/carsReducer.js, server/routes/carRoute.js
Car details render to page after clicking details button.
Resolves #94
=> Worked on CarsDetails

client/src/components/SignUp.js
- setup pattern attribute to validate all fields
- wrote function to validate that password and confirm_password inputs match before pinging the server
- validation only catches mismatched passwords on second attempt
- first attempt it pings the server and the server catches the error
resolves #59
=> Finishing up validation

client/src/components/CarsForm.js
Clear previous results when starting a new search.
Resolves #98
=> Add ClearCars to CarsForm

client/src/components/Cars.js, client/src/components/Itinerary.js, client/src/redux/reducers/usersReducer.js
- add car detail to itinerary page
- created function to handle data coming from hotel and car component
- if hotel and/or car object is empty it will render a message that a hotel/car was not selected
- otherwise hotel and car details will render to page
resolves #59
=> Add Car Detail to Itinerary

client/src/redux/reducers/flightsReducer.js
Added missing bracket and fixed spacing.
Resolves #103
=> Edited FlightsReducer

server/migrations/20170430060221-update-car-table.js, server/migrations/20170430061934-update-flight-table.js, server/migrations/20170430062642-update-hotel-table.js, server/migrations/20170430064042-update-hotel-table.js, server/migrations/20170430064224-update-flight-table.js, server/models/car.js, server/models/flight.js, server/models/hotel.js
- updated Car table
- updated Hotel table
- updated Flight table
resolves #111
=> Update Columns in Tables

client/public/css/app.css, client/scss/app.scss, client/scss/partials/flight.scss, client/src/components/CarsForm.js, client/src/components/FlightDetails.js, client/src/components/Flights.js, client/src/components/FlightsForm.js, client/src/components/HotelsForm.js, client/src/components/Itinerary.js, client/src/containers/App.js, server/server.js
- fixed flight layout in listing and details
- added flight info to itinerary
- updated hotel info in itinerary
resolves #115
=> Update Web Layouts

.gitignore, client/public/css/app.css, client/scss/app.scss, client/scss/partials/car.scss, client/scss/partials/flight.scss, client/scss/partials/globe.scss, client/scss/partials/hotel.scss, client/scss/partials/itinerary.scss, client/scss/partials/nav.scss, client/scss/partials/sidebar.scss, client/scss/partials/user.scss, client/scss/partials/variables.scss, client/src/components/FlightsForm.js, client/src/components/Nav.js, client/src/components/Sidebar.js, client/src/components/SignIn.js, client/src/components/SignUp.js, client/src/containers/App.js, client/src/index.js
- add variable for card layout
- working on form layout variables
- reformatting flight form
- styled user profile
resolves #115
=> Styling Web App

client/public/css/app.css, client/scss/app.scss, client/scss/partials/flight.scss, client/scss/partials/variables.scss, client/src/components/Flights.js, client/src/components/FlightsForm.js
- styled a little more on the flight form
- styled the flight list results while Gina styled hotel results so we can get some standard styles for the variable file
resolves #115
=> Style Standardization

client/public/css/app.css, client/scss/app.scss, client/scss/partials/flight.scss, client/scss/partials/itinerary.scss, client/scss/partials/user.scss, client/src/components/Itinerary.js, client/src/components/SignIn.js, client/src/components/SignUp.js
- fixed issues
- styled signin and signup
resolves #115
=> Updated the forms and refined the itinerary page

client/public/css/app.css, client/scss/partials/car.scss, client/scss/partials/flight.scss, client/src/components/Cars.js, client/src/components/FlightDetails.js
=> Added additional styling.

client/public/css/app.css, client/scss/app.scss, client/src/containers/App.js
- stretched home page image across window
- increased size of plan adventure button
resolves #115
=> Refined Home Page

client/public/css/app.css, client/scss/app.scss
- Moved the submit button for the home page into the id home so it doesn't affect the other buttons.
resolves #115
=> Moved Home Page Button

client/public/css/app.css, client/scss/app.scss, client/scss/partials/variables.scss
- Fixed height in variables. Adjusted margin top for homepage pic.
resolves #115
=> Fixed Things

client/public/css/app.css, client/scss/partials/car.scss, client/scss/partials/flight.scss, client/scss/partials/hotel.scss, client/src/components/Cars.js, client/src/components/CarsDetails.js, client/src/components/FlightDetails.js, client/src/components/Flights.js, client/src/components/HotelDetail.js, client/src/components/Hotels.js
=> Styled buttons.

client/public/css/app.css, client/scss/partials/itinerary.scss, client/src/components/Itinerary.js, client/src/components/SignIn.js
- added links to itinerary
- removed reset password link; not ready to deploy
resolves #115
=> Refine Styling

client/public/css/app.css, client/scss/app.scss, client/scss/partials/car.scss, client/scss/partials/flight.scss, client/scss/partials/hotel.scss, client/scss/partials/itinerary.scss, client/scss/partials/user.scss, client/src/components/HotelDetail.js, client/src/components/Itinerary.js
-Added pointer to button styling so a pointer appears when button is moused over. -Added dollar symbol to hotel detail. Fixed other things.
resolves #115
=> Refined Styling and Buttons
